### ISSUE TITLE
Bonus are great but not in french

### ISSUE THREAD

**Issue by villa-rose** [teuteuf/worldle#334] opened 2022-10-18 09:47 UTC
Thank you four the bonuses, they add fun on top of fun. Unfortunately they don't work in French (e.g the drop menu proposes REPUBLIQUE DOMINICAINE noted wrong when the correct answer is DOMINICAN REPUBLIC)

**Comment by teuteuf** [comment] 2022-10-18 11:26
Duplicate of #332
We are working on a fix and will keep you posted when the bonus round works correctly!
Sorry about that!

**Closed** 2022-10-18 11:26 UTC
