### ISSUE TITLE
Seeing different countries on different browsers

### ISSUE THREAD

**Issue by dslgr** [teuteuf/worldle#150] opened 2022-03-28 15:37 UTC
On iOS safari I'm seeing this today and it shares as #66:
![image](https://user-images.githubusercontent.com/30943714/160434607-9ce6fe43-5277-4bca-8ecf-f3ffa2a99d2d.jpeg)

On private mode iOS safari I'm seeing this:
![image](https://user-images.githubusercontent.com/30943714/160434687-6b3faf25-76cc-4d0b-81f1-e532d8f3194d.jpeg)

I think for several days I'm seeing different countries. On Friday the country was Saint Helena while on the internet archive I'm seeing a completely different country.

**Comment by Teej42** [comment] 2022-03-28 16:17
We're seeing the same thing here.

**Comment by MetalManiacMc** [comment] 2022-03-28 17:08
I can confirm. Clearing the cache doesn't change anything.

**Comment by teuteuf** [comment] 2022-03-28 17:13
On PC, Ctrl+F5 should work too.

On Firefox Android, a long press on the refresh button does the trick too.

But on other web browsers... Close all and reopen it a few times... 🫤

**Comment by hugoread** [comment] 2022-03-28 17:38
We have a group of six friends doing this every day. 3 of them also got St. Helena (wrong Country) instead of Sweden. It's very strange and kind of kills the game unfortunately. The next day 5 of the six had Vanuatu (right country) but two had Samoa! Then a couple of days ago, most of us got French Overseas Territories, but two of us got Togo!

**Comment by teuteuf** [comment] 2022-04-02 23:32
It is caused by app not refreshed correctly.

I hope it is fixed now, it should be fixed after closing/reopening the app a few time.

I also updated how the app get refreshed, it should improve things...

**Comment by teuteuf** [comment] 2022-04-02 23:32
I close this issue, let me know if you still observe problem.

**Closed by teuteuf** 2022-04-02 23:32 UTC
