### ISSUE TITLE
anonymize country name in image path

### ISSUE THREAD

**Issue by spmsh** [teuteuf/worldle#59] opened 2022-03-01 16:12 UTC
country initials are not anonymized in the html, could guess what country it is by this means

for instance with Uruguay: images/countries/**uy**/vector.svg

![image](https://user-images.githubusercontent.com/36556605/156205376-6c04a85c-24f2-4ae9-9497-5dbbc487b60d.png)

**Comment by kegelkugel** [comment] 2022-03-10 12:17
I agree with this bug report. In the mobile browser DuckDuckGo, it's even sufficient to make a long click on the map to see the country's abbreviation, which can be a very clear hint.
![Screenshot_20220310-131502](https://user-images.githubusercontent.com/29691621/157659916-01292504-fbe9-4f6a-8bf2-5e6135d22a18.png)
In the screenshot, one can see the initials"gr", which stand for Greece.

**Comment by spmsh** [comment] 2022-03-12 06:03
actually even easier if you open the image in another new tab, the name of the country is displayed in the tab title

![image](https://user-images.githubusercontent.com/36556605/158006181-ac68efc4-3785-4102-98da-37d1e4d639af.png)

**Comment by dougaitken** [comment] 2022-03-12 09:47
> actually even easier if you open the image in another new tab, the name of the country is displayed in the tab title

This ruined it for me today. It’s obvious from the previous comments that the image path contains the alpha-2 code the country but no need to add more examples like todays. 

I should have finished todays before checking this project so my fault. 

Also, why spoil it for yourself, you don’t have to check image paths and such, just do the quiz?

**Comment by dougaitken** [comment] 2022-03-12 09:57
Actually, this is a duplicate of #28

**Closed** 2022-03-13 16:45 UTC
