### ISSUE TITLE
Flagle, please!

### ISSUE THREAD

**Issue by da-viid** [teuteuf/worldle#185] opened 2022-04-16 16:22 UTC
I would love to play a version in which the user can see the flag of the country instead of the outline. Ideally, I would like the ability to set the puzzle to display the map, flag or both.

**Comment by dtsch** [comment] 2022-04-22 14:37
Seconded

**Comment by Ssnarf** [comment] 2022-04-28 07:23
Something like this already exists. Not exactly as you requested but similar.
https://www.flagle.io/

**Comment by dtsch** [comment] 2022-04-28 12:52
Nice find. Like you mentioned, not exactly as requested, but still quite good.

Would still be a dream to have it as an option in Worldle, or even at the very least have the flag show up once guessed correctly

**Comment by 9ps** [comment] 2022-05-17 04:10
a better iteration of a "flag wordle game" is [this flaggle](https://ducc.pythonanywhere.com/flaggle/)

**Comment by bobpaul** [comment] 2022-06-02 16:46
I think this is a duplicate of issue #42

**Closed** 2022-06-07 21:07 UTC
