### ISSUE TITLE
Border countries wrongfully considered incorrect

### ISSUE THREAD

**Issue by pbourdet** [teuteuf/worldle#333] opened 2022-10-16 12:22 UTC
During today's question about border countries of Burundi, both Tanzania and RDC were considered wrong even though they actually were the right answers  : (maybe an issue with language since I have the countries list in French)

![image](https://user-images.githubusercontent.com/52003151/196035134-52ee24b9-fab5-4197-b9c4-efd991d9db8c.png)

**Comment by webfil** [comment] 2022-10-16 13:53
Same problem.
![Screenshot_20221016-095009](https://user-images.githubusercontent.com/81570987/196039238-e29cfa2e-0081-49d6-9ee5-b1cec13f5da1.jpg)

**Comment by ThomasIdgeo** [comment] 2022-10-17 11:02
Same for me in french
![image](https://user-images.githubusercontent.com/65945567/196161362-15ca8308-e16e-4a03-9b63-90c1ca4493b6.png)

**Comment by paferrat** [comment] 2022-10-18 11:18
Same problem with the last three bonus rounds. Country names in German. Only one country has been accepted as correct although all the countries were correct.

**Comment by teuteuf** [comment] 2022-10-18 11:23
Duplicate of the issue #332
We're working on a fix and will keep you posted when it will be fixed!
Sorry for the inconvenience!

**Closed** 2022-10-18 11:24 UTC

**Comment by PooteeOfficiel** [comment] 2022-10-19 10:09
![image](https://user-images.githubusercontent.com/112540946/196662629-030a7e4e-c01d-4637-ab8c-aa2efd3246d1.png)
